# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alamofire_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for Alamofire_Study

  target 'Alamofire_StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Alamofire_StudyUITests' do
    # Pods for testing
  end

end
